version: '1.0'

services:
  master:
    image: distributed_log:1.0
    ports:
      - "3000:3000"
      - "4000:50051"
  
  # app_instance2:
  #   image: my-python-app
  #   environment:
  #     - APP_PORT2=3001
  #   ports:
  #     - "3001:3001"