version: '1.1'

services:
  master:
    image: ghcr.io/houstoten/distributed_log:latest
    ports:
      - "3000:3000"
    environment:
      - MASTER=-m
      - REPLICAS=-s localhost:50051
  
  secondary:
    image: ghcr.io/houstoten/distributed_log:latest
    ports:
      - "3001:3000"
      - "50051:50051"
    environment:
      - MASTER=
      - REPLICAS=
