# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_send_pb2 as message__send__pb2


class ReceiverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewMessage = channel.unary_unary(
                '/Receiver/NewMessage',
                request_serializer=message__send__pb2.Msg.SerializeToString,
                response_deserializer=message__send__pb2.Empty.FromString,
                )


class ReceiverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.NewMessage,
                    request_deserializer=message__send__pb2.Msg.FromString,
                    response_serializer=message__send__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Receiver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Receiver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Receiver/NewMessage',
            message__send__pb2.Msg.SerializeToString,
            message__send__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
