# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sync_replica.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sync_replica.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12sync_replica.proto\"\x1e\n\x07OneBeat\x12\x13\n\x0bwas_missing\x18\x01 \x01(\x08\"\"\n\rKnownMessages\x12\x11\n\tknown_ids\x18\x01 \x03(\r\"-\n\x0eMissedMessages\x12\x0b\n\x03ids\x18\x01 \x03(\r\x12\x0e\n\x06values\x18\x02 \x03(\t\"\x0b\n\tBoolEmpty2d\n\x0bSyncReplica\x12\'\n\tHeartBeat\x12\x08.OneBeat\x1a\x0e.KnownMessages\"\x00\x12,\n\x0b\x42\x61tchUpdate\x12\x0f.MissedMessages\x1a\n.BoolEmpty\"\x00\x62\x06proto3'
)




_ONEBEAT = _descriptor.Descriptor(
  name='OneBeat',
  full_name='OneBeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='was_missing', full_name='OneBeat.was_missing', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=52,
)


_KNOWNMESSAGES = _descriptor.Descriptor(
  name='KnownMessages',
  full_name='KnownMessages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='known_ids', full_name='KnownMessages.known_ids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=88,
)


_MISSEDMESSAGES = _descriptor.Descriptor(
  name='MissedMessages',
  full_name='MissedMessages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='MissedMessages.ids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='MissedMessages.values', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=135,
)


_BOOLEMPTY = _descriptor.Descriptor(
  name='BoolEmpty',
  full_name='BoolEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['OneBeat'] = _ONEBEAT
DESCRIPTOR.message_types_by_name['KnownMessages'] = _KNOWNMESSAGES
DESCRIPTOR.message_types_by_name['MissedMessages'] = _MISSEDMESSAGES
DESCRIPTOR.message_types_by_name['BoolEmpty'] = _BOOLEMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OneBeat = _reflection.GeneratedProtocolMessageType('OneBeat', (_message.Message,), {
  'DESCRIPTOR' : _ONEBEAT,
  '__module__' : 'sync_replica_pb2'
  # @@protoc_insertion_point(class_scope:OneBeat)
  })
_sym_db.RegisterMessage(OneBeat)

KnownMessages = _reflection.GeneratedProtocolMessageType('KnownMessages', (_message.Message,), {
  'DESCRIPTOR' : _KNOWNMESSAGES,
  '__module__' : 'sync_replica_pb2'
  # @@protoc_insertion_point(class_scope:KnownMessages)
  })
_sym_db.RegisterMessage(KnownMessages)

MissedMessages = _reflection.GeneratedProtocolMessageType('MissedMessages', (_message.Message,), {
  'DESCRIPTOR' : _MISSEDMESSAGES,
  '__module__' : 'sync_replica_pb2'
  # @@protoc_insertion_point(class_scope:MissedMessages)
  })
_sym_db.RegisterMessage(MissedMessages)

BoolEmpty = _reflection.GeneratedProtocolMessageType('BoolEmpty', (_message.Message,), {
  'DESCRIPTOR' : _BOOLEMPTY,
  '__module__' : 'sync_replica_pb2'
  # @@protoc_insertion_point(class_scope:BoolEmpty)
  })
_sym_db.RegisterMessage(BoolEmpty)



_SYNCREPLICA = _descriptor.ServiceDescriptor(
  name='SyncReplica',
  full_name='SyncReplica',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=150,
  serialized_end=250,
  methods=[
  _descriptor.MethodDescriptor(
    name='HeartBeat',
    full_name='SyncReplica.HeartBeat',
    index=0,
    containing_service=None,
    input_type=_ONEBEAT,
    output_type=_KNOWNMESSAGES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BatchUpdate',
    full_name='SyncReplica.BatchUpdate',
    index=1,
    containing_service=None,
    input_type=_MISSEDMESSAGES,
    output_type=_BOOLEMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYNCREPLICA)

DESCRIPTOR.services_by_name['SyncReplica'] = _SYNCREPLICA

# @@protoc_insertion_point(module_scope)
